const PRIORITY={foreground:0,refresh:1,background:1,export:2};
const abortError=message=>Object.assign(new Error(message||'Aborted'),{name:'AbortError'});

export class PermitBroker{
  constructor({perHost=4,maxExport=1}={}){this.perHost=Math.max(1,Number(perHost)||4);this.maxExport=Math.max(1,Number(maxExport)||1);this.hostActive=new Map();this.activeExport=0;this.queue=[];this.leases=new Map();this.seq=0;this.leaseSeq=0;this.closed=false}
  normalizeHost(host){const raw=String(host||'').trim();if(!raw)throw new Error('Permit host is required');try{return new URL(raw.includes('://')?raw:`https://${raw}`).host}catch{return raw}}
  acquire(host,{purpose='refresh',ownerId='default',signal}={}){
    if(this.closed)return Promise.reject(new Error('Permit broker closed'));host=this.normalizeHost(host);purpose=Object.hasOwn(PRIORITY,purpose)?purpose:'refresh';ownerId=String(ownerId||'default');
    return new Promise((resolve,reject)=>{const item={host,purpose,ownerId,resolve,reject,seq:++this.seq,signal,aborted:false,abort:null};item.abort=()=>{if(item.aborted)return;item.aborted=true;this.queue=this.queue.filter(x=>x!==item);reject(abortError());this.pump()};if(signal){if(signal.aborted){item.abort();return}signal.addEventListener('abort',item.abort,{once:true})}this.queue.push(item);this.pump()})
  }
  canGrant(item){return (this.hostActive.get(item.host)||0)<this.perHost&&(item.purpose!=='export'||this.activeExport<this.maxExport)}
  pump(){if(this.closed)return;this.queue.sort((a,b)=>PRIORITY[a.purpose]-PRIORITY[b.purpose]||a.seq-b.seq);let progressed=true;while(progressed){progressed=false;const index=this.queue.findIndex(item=>!item.aborted&&this.canGrant(item));if(index<0)break;const item=this.queue.splice(index,1)[0];if(item.signal)item.signal.removeEventListener('abort',item.abort);const id=`permit-${++this.leaseSeq}`;const lease={id,host:item.host,purpose:item.purpose,ownerId:item.ownerId,released:false};this.leases.set(id,lease);this.hostActive.set(item.host,(this.hostActive.get(item.host)||0)+1);if(item.purpose==='export')this.activeExport++;item.resolve(Object.freeze({id,host:item.host,purpose:item.purpose,ownerId:item.ownerId,release:()=>this.release(id)}));progressed=true}}
  release(id){const lease=this.leases.get(String(id));if(!lease||lease.released)return false;lease.released=true;this.leases.delete(lease.id);const active=Math.max(0,(this.hostActive.get(lease.host)||0)-1);if(active)this.hostActive.set(lease.host,active);else this.hostActive.delete(lease.host);if(lease.purpose==='export')this.activeExport=Math.max(0,this.activeExport-1);this.pump();return true}
  releaseOwner(ownerId,{rejectQueued=true}={}){ownerId=String(ownerId||'');if(!ownerId)return 0;let count=0;for(const [id,lease] of [...this.leases])if(lease.ownerId===ownerId){this.release(id);count++}if(rejectQueued){const doomed=this.queue.filter(x=>x.ownerId===ownerId);this.queue=this.queue.filter(x=>x.ownerId!==ownerId);for(const item of doomed){item.aborted=true;if(item.signal)item.signal.removeEventListener('abort',item.abort);item.reject(abortError('Permit owner released'));count++}}this.pump();return count}
  snapshot(){return {perHost:this.perHost,maxExport:this.maxExport,activeExport:this.activeExport,hostActive:Object.fromEntries(this.hostActive),queued:this.queue.map(x=>({host:x.host,purpose:x.purpose,ownerId:x.ownerId,seq:x.seq})),leases:[...this.leases.values()].map(x=>({id:x.id,host:x.host,purpose:x.purpose,ownerId:x.ownerId}))}}
  close(){if(this.closed)return;this.closed=true;for(const item of this.queue){item.aborted=true;if(item.signal)item.signal.removeEventListener('abort',item.abort);item.reject(new Error('Permit broker closed'))}this.queue=[];for(const id of [...this.leases.keys()])this.release(id);this.leases.clear();this.hostActive.clear();this.activeExport=0}
}
